version: "3.6"
services:
  postgres:
    image: postgres:14
    restart: always
    ports:
      - 8999:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
